In [81]:
import torch
import torch.nn as nn

In [82]:
tensor_bs = torch.randn([32, 200, 21, 81])

In [83]:
ADJ_MATRIX = torch.tensor([
    #0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
    [0, 1, 0, 0, 0, 1, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [1, 0, 0, 0, 0, 0, 1, 0, 0, 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
]).float()

In [84]:
ADJ_MATRIX.matmul(tensor_bs[0][0])

tensor([[ 0.7913, -1.2799,  1.0649,  ...,  1.1212, -0.9844,  3.8166],
        [ 1.8020,  0.4387,  0.0179,  ...,  0.7022,  2.1537,  0.8907],
        [-0.4823,  0.0391,  2.2809,  ...,  2.7894, -0.4802, -0.5259],
        ...,
        [ 0.3457,  0.9914, -2.0438,  ...,  0.5141,  0.4909,  1.9305],
        [-0.3886,  0.3280,  0.2514,  ..., -2.2043, -0.9087,  1.9410],
        [ 0.3335,  1.3825, -2.1018,  ...,  0.4934,  1.0639, -0.5530]])

In [85]:

ADJ_MATRIX/ADJ_MATRIX.sum(axis=1)

tensor([[0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.3333, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3333,
         0.0000, 0.0000, 0.0000],
        [0.3333, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.3333, 0.0

In [86]:
torch.eye(ADJ_MATRIX.shape[0])

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 

In [87]:
torch.cat(tensor_bs.split(tensor_bs.shape[1], dim=0), dim=0).shape

torch.Size([32, 200, 21, 81])

In [88]:
list(tensor_bs.split(200, dim=-1))

[tensor([[[[ 8.3174e-01, -5.5769e-01, -7.0840e-02,  ...,  2.2907e-01,
             1.7204e+00,  5.2322e-01],
           [-1.6266e-02,  2.9383e-01,  2.9387e-01,  ...,  1.2558e+00,
            -6.0328e-01,  1.0730e+00],
           [ 9.7021e-01,  9.9642e-01,  8.8701e-02,  ...,  4.7312e-01,
             4.3322e-01,  3.6744e-01],
           ...,
           [-1.1835e-01, -3.5474e-01, -3.2846e-01,  ..., -1.4446e+00,
            -3.2672e-01,  1.9703e+00],
           [ 3.3351e-01,  1.3825e+00, -2.1018e+00,  ...,  4.9344e-01,
             1.0639e+00, -5.5295e-01],
           [-2.7029e-01,  6.8271e-01,  5.7987e-01,  ..., -7.5969e-01,
            -5.8197e-01, -2.9324e-02]],
 
          [[ 4.7335e-01,  6.3424e-01, -5.3964e-01,  ...,  4.0511e-01,
            -7.5154e-01, -8.6177e-01],
           [ 2.0142e-01,  7.3251e-01,  6.3247e-01,  ...,  2.6947e-01,
            -5.8127e-01, -1.4453e+00],
           [-8.2456e-01, -1.1907e-01,  6.8516e-01,  ...,  1.2617e+00,
             5.6240e-02, -4.5229e-01],


In [89]:
aa = nn.ReLU()

aa(tensor_bs)

tensor([[[[8.3174e-01, 0.0000e+00, 0.0000e+00,  ..., 2.2907e-01,
           1.7204e+00, 5.2322e-01],
          [0.0000e+00, 2.9383e-01, 2.9387e-01,  ..., 1.2558e+00,
           0.0000e+00, 1.0730e+00],
          [9.7021e-01, 9.9642e-01, 8.8701e-02,  ..., 4.7312e-01,
           4.3322e-01, 3.6744e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 1.9703e+00],
          [3.3351e-01, 1.3825e+00, 0.0000e+00,  ..., 4.9344e-01,
           1.0639e+00, 0.0000e+00],
          [0.0000e+00, 6.8271e-01, 5.7987e-01,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00]],

         [[4.7335e-01, 6.3424e-01, 0.0000e+00,  ..., 4.0511e-01,
           0.0000e+00, 0.0000e+00],
          [2.0142e-01, 7.3251e-01, 6.3247e-01,  ..., 2.6947e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 6.8516e-01,  ..., 1.2617e+00,
           5.6240e-02, 0.0000e+00],
          ...,
          [3.0326e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000

In [90]:
torch.cat(torch.split(tensor_bs, 1, dim=1), dim=0).shape

torch.Size([6400, 1, 21, 81])

In [91]:
a = torch.arange(16).reshape(2,2,2,2)
splited_tensor = torch.split(a,1, dim=1)

In [92]:
tmp_merged = torch.cat(splited_tensor, dim=0).squeeze(1)

In [93]:
tmp_merged.shape

torch.Size([4, 2, 2])

In [94]:
tmp_merged1 = tmp_merged + 1

In [95]:
torch.cat(tmp_merged1.unsqueeze(1).split(2, dim=0), dim=1).shape

torch.Size([2, 2, 2, 2])

In [96]:
tmp_merged1.unsqueeze(1).shape

torch.Size([4, 1, 2, 2])

In [97]:
import torch
b = torch.arange(24).reshape(2,3,4)

In [98]:
b

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [99]:
b.shape

torch.Size([2, 3, 4])

In [100]:
b.permute(1,0,2)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

In [101]:
import torch.nn as nn
import torch

# Target are to be un-padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)

# Initialize random batch of targets (0 = blank, 1:C = classes)
target_lengths = torch.randint(low=1, high=T, size=(N,), dtype=torch.long)
target = torch.randint(low=1, high=C, size=(sum(target_lengths),), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()

In [102]:
input.shape, input_lengths.shape, target_lengths.shape

(torch.Size([50, 16, 20]), torch.Size([16]), torch.Size([16]))

In [103]:
input_lengths

tensor([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [104]:
target

tensor([19,  5,  4,  4, 15, 15,  8,  7,  3, 19, 19,  8,  3, 14, 17,  8, 12,  2,
        13, 16, 16, 12, 16, 11,  9, 19,  2, 13,  7,  1,  3, 10, 13, 12, 10,  6,
         9, 14, 12,  1, 11, 10, 14,  9, 17,  1, 10, 17,  3, 17,  6,  3,  3,  4,
         3,  3,  1, 13, 10, 10, 16,  9,  9,  9,  8,  3,  2, 17,  1,  8,  9,  9,
        12, 14,  2, 16, 19,  2, 19,  4,  5, 17, 18,  2,  7,  2, 16,  4, 16, 14,
        12, 14,  3,  8,  7,  7,  9, 18, 19,  9, 11,  9, 18, 12, 15,  7, 15,  3,
        15,  6, 14, 15, 12, 15, 12, 19,  8, 16,  8,  2, 13, 13,  7, 15,  6,  4,
        11, 15,  4,  6, 19,  7, 13, 11,  4, 18,  6, 11,  9,  4, 15,  7, 11, 11,
        11,  4,  2,  2, 19, 13, 19, 12, 18, 16, 17, 16,  9,  4, 17, 18,  1,  1,
         4, 11, 12,  6,  3, 13,  8,  8,  5,  5,  5,  9,  2,  1, 18, 11, 12, 16,
         3, 10,  5,  4,  3,  5,  2, 19, 12, 16, 16, 18,  1, 18,  4,  5,  4,  7,
         1,  5, 19, 13,  9, 16, 17,  4,  2,  4, 14,  2,  6, 11,  2,  4,  4, 13,
         6, 14,  2, 13,  7,  1,  7, 19, 

In [105]:
input.log_softmax(dim=-1).argmax(dim=-1)

tensor([[ 5, 11, 11, 14, 18,  7,  7, 11, 13,  8,  2, 18, 12,  0, 12,  9],
        [ 9,  8, 19, 18,  0,  4, 10, 19, 17, 16,  0,  3, 11, 18, 10,  9],
        [15, 14, 12,  8, 17, 19,  5, 13, 15,  3,  4, 19, 15,  7, 15, 10],
        [ 7, 10, 15,  6, 15,  6, 12,  9,  0, 16,  7,  9,  9, 16,  9, 12],
        [ 7,  1, 18,  2,  9,  0, 10, 11,  9,  7,  7,  6,  6,  1,  6, 16],
        [17,  8, 13, 12,  4, 19, 14,  4,  3,  5, 18,  1, 12, 14,  4,  3],
        [ 3,  3,  9,  7,  7,  0,  8, 19,  1, 10, 19,  1,  5, 12, 16, 11],
        [17,  7,  2, 14,  5,  9, 17, 17,  3, 18,  0,  9,  8, 18, 16,  2],
        [18, 15, 12, 18,  8,  3,  1, 13, 14,  1, 13,  0, 12,  8,  2,  3],
        [10,  4, 11, 14,  1,  5, 10, 14,  3, 16, 15, 12,  0,  9, 17,  1],
        [ 4, 12, 12,  7,  3, 14, 10, 17,  0,  0, 19, 18,  4, 19,  9,  8],
        [ 8, 14, 10,  9, 17,  0,  3, 10, 19, 17,  7,  8,  1,  4, 10,  0],
        [12, 17, 11, 13,  7,  9,  3, 15,  1, 17,  0,  3,  1,  1,  4,  5],
        [ 8,  2,  7,  5, 15,  0,  3,  

In [106]:
import pandas as pd
dd = pd.read_parquet("/data/finger/data/train_landmarks/169560558.parquet")

In [107]:
len(dd)

158482

In [1]:
import pandas as pd
import random
import numpy as np

train_fn = '/data/finger/data/supplemental_possible.parquet'
supplementary_fn = '/data/finger/data/train_possible.parquet'
train_landmark01 = '/data/finger/data/partial_train_landmark01.parquet'
supplementary_landmark01 = '/data/finger/data/partial_supplemental_landmark01.parquet'
n_parts = 10

train_df = pd.concat([pd.read_parquet(train_fn)[['path','file_id','sequence_id','phrase']], 
                      pd.read_parquet(supplementary_fn)[['path','file_id','sequence_id','phrase']]])
lookup_df = pd.concat([pd.read_parquet(train_landmark01), 
                       pd.read_parquet(supplementary_landmark01)])
# train_df = pd.concat([train, supplementary])
# lookup_df = pd.concat([train_landmark, supp_landmark])


In [ ]:
lookup_df

sequence_id  frame  x_right_hand_0  x_right_hand_1  x_right_hand_2  \
0         450271163      0             NaN             NaN             NaN   
1         450271163      1             NaN             NaN             NaN   
2         450271163      2             NaN             NaN             NaN   
3         450271163      3             NaN             NaN             NaN   
4         450271163      4             NaN             NaN             NaN   
...             ...    ...             ...             ...             ...   
170606   2022137216    155             NaN             NaN             NaN   
170607   2022137216    156             NaN             NaN             NaN   
170608   2022137216    157             NaN             NaN             NaN   
170609   2022137216    158             NaN             NaN             NaN   
170610   2022137216    159        0.289102        0.441571        0.562708   

        x_right_hand_3  x_right_hand_4  x_right_hand_5  x_right_hand_6  \
0                  NaN             NaN             NaN             NaN   
1                  NaN             NaN             NaN             NaN   
2                  NaN             NaN             NaN             NaN   
3                  NaN             NaN             NaN             NaN   
4                  NaN             NaN             NaN             NaN   
...                ...             ...             ...             ...   
170606             NaN             NaN             NaN             NaN   
170607             NaN             NaN             NaN             NaN   
170608             NaN             NaN             NaN             NaN   
170609             NaN             NaN             NaN             NaN   
170610        0.645995        0.703535        0.625442        0.761709   

        x_right_hand_7  ...  z_left_hand_11  z_left_hand_12  z_left_hand_13  \
0                  NaN  ...       -0.131148       -0.153634       -0.093264   
1                  NaN  ...       -0.108135       -0.126339       -0.084145   
2                  NaN  ...       -0.131652       -0.153116       -0.102476   
3                  NaN  ...       -0.102535       -0.124609       -0.075734   
4                  NaN  ...       -0.021602       -0.034823       -0.036247   
...                ...  ...             ...             ...             ...   
170606             NaN  ...             NaN             NaN             NaN   
170607             NaN  ...             NaN             NaN             NaN   
170608             NaN  ...             NaN             NaN             NaN   
170609             NaN  ...             NaN             NaN             NaN   
170610        0.854497  ...             NaN             NaN             NaN   

        z_left_hand_14  z_left_hand_15  z_left_hand_16  z_left_hand_17  \
0            -0.145342       -0.195751       -0.230883       -0.110699   
1            -0.131306       -0.178627       -0.213141       -0.102693   
2            -0.154591       -0.205599       -0.242489       -0.124570   
3            -0.123845       -0.169882       -0.203251       -0.100899   
4            -0.069445       -0.115044       -0.150894       -0.059755   
...                ...             ...             ...             ...   
170606             NaN             NaN             NaN             NaN   
170607             NaN             NaN             NaN             NaN   
170608             NaN             NaN             NaN             NaN   
170609             NaN             NaN             NaN             NaN   
170610             NaN             NaN             NaN             NaN   

        z_left_hand_18  z_left_hand_19  z_left_hand_20  
0            -0.176297       -0.208744       -0.228749  
1            -0.163479       -0.193422       -0.213809  
2            -0.184529       -0.212316       -0.231991  
3            -0.163232       -0.191301       -0.209427  
4            -0.102723       -0.125831       -0.144639  
..

In [ ]:
paths = train_df.path.unique().tolist()
np.random.shuffle(paths)
paths = np.array_split(paths,3)
RIGHT_HAND = []
LEFT_HAND = []
for i in range(21):
    RIGHT_HAND += [f'x_right_hand_{i}', f'y_right_hand_{i}', f'z_right_hand_{i}']
    LEFT_HAND += [f'x_left_hand_{i}', f'y_left_hand_{i}', f'z_left_hand_{i}']

for idx,path in enumerate(paths):
    pd.concat([pd.read_parquet("./data/" + p)[RIGHT_HAND+LEFT_HAND] for p in path]).to_parquet(f"frame{idx}.parquet")
    train_df.set_index("path").loc[path].to_parquet(f"partial_train_{idx}.parquet")


In [ ]:
pd.read_parquet("./data/" + path[0])

frame  x_face_0  x_face_1  x_face_2  x_face_3  x_face_4  \
sequence_id                                                            
289455001        0  0.534934  0.534527  0.535548  0.524667  0.534588   
289455001        1  0.537000  0.535850  0.537012  0.526591  0.536014   
289455001        2  0.538147  0.537990  0.539020  0.528827  0.538208   
289455001        3  0.537752  0.538154  0.539238  0.528891  0.538350   
289455001        4  0.537880  0.539046  0.539835  0.529835  0.539342   
...            ...       ...       ...       ...       ...       ...   
322991127      206  0.527276  0.519772  0.523732  0.504643  0.518648   
322991127      207  0.532123  0.521891  0.526034  0.506228  0.520529   
322991127      208  0.534424  0.526392  0.530648  0.511264  0.525103   
322991127      209  0.537075  0.527680  0.532107  0.512697  0.526478   
322991127      210  0.533943  0.527466  0.531415  0.512077  0.526281   

             x_face_5  x_face_6  x_face_7  x_face_8  ...  z_right_hand_11  \
sequence_id                                          ...                    
289455001    0.535570  0.538703  0.439157  0.539747  ...        -0.105665   
289455001    0.537297  0.541254  0.439973  0.542760  ...        -0.141822   
289455001    0.539518  0.543461  0.442049  0.545013  ...        -0.135338   
289455001    0.539595  0.543315  0.441052  0.544721  ...        -0.120654   
289455001    0.540623  0.544334  0.441271  0.545839  ...        -0.113321   
...               ...       ...       ...       ...  ...              ...   
322991127    0.518838  0.520733  0.402911  0.519971  ...              NaN   
322991127    0.520499  0.522067  0.406616  0.521032  ...              NaN   
322991127    0.525262  0.527418  0.411823  0.526731  ...              NaN   
322991127    0.526757  0.529058  0.411852  0.528442  ...        -0.053320   
322991127    0.526370  0.527963  0.411306  0.526944  ...        -0.123308   

             z_right_hand_12  z_right_hand_13  z_right_hand_14  \
sequence_id                                                      
289455001          -0.118246        -0.056129        -0.089398   
289455001          -0.151405        -0.078584        -0.123392   
289455001          -0.140751        -0.062080        -0.107539   
289455001          -0.125383        -0.049615        -0.088004   
289455001          -0.116131        -0.049567        -0.088013   
...                      ...              ...              ...   
322991127                NaN              NaN              NaN   
322991127                NaN              NaN              NaN   
322991127                NaN              NaN              NaN   
322991127          -0.064666        -0.037329        -0.071830   
322991127          -0.117959        -0.068203        -0.132773   

             z_right_hand_15  z_right_hand_16  z_right_hand_17  \
sequence_id                                                      
289455001          -0.108088        -0.116833        -0.073612   
289455001          -0.143080        -0.150590        -0.089088   
289455001          -0.120657        -0.121316        -0.078355   
289455001          -0.098717        -0.098701        -0.064544   
289455001          -0.097065        -0.095067        -0.066377   
...                      ...              ...              ...   
322991127                NaN              NaN              NaN   
322991127                NaN              NaN              NaN   
322991127                NaN              NaN              NaN   
322991127          -0.082154        -0.082143        -0.070344   
322991127          -0.125696        -0.103179        -0.097390   

             z_right_hand_18  z_right_hand_19  z_right_hand_20  
sequence_id                                                     
289455001          -0.099701        -0.114585        -0.123557  
289455001          -0.130970        -0.156410        -0.171756  
289455001          -0.114807        -0.130914        -0.137566  
289455001          -0.090260   

In [ ]:
torch.save(dataloader_obj, 'dataloader.pth')

path     file_id  sequence_id  \
64222  train_landmarks/2072296290.parquet  2072296290     66717045   

                    phrase  
64222  www.arturostore.com

In [ ]:
train_df[train_df['sequence_id'] == 66954152]

path     file_id  sequence_id  \
64234  train_landmarks/2072296290.parquet  2072296290     66954152   

                            phrase  
64234  www.sincensuradeportiva.com

In [ ]:
import pandas as pd

aa = pd.read_parquet("./data/frame1.parquet")

In [ ]:
aa[aa['x_right_hand_0'] < 0.1]

x_right_hand_0  y_right_hand_0  z_right_hand_0  x_right_hand_1  \
sequence_id                                                                   
1654240258         0.084626        0.813477    7.677165e-07        0.166219   
1654240258         0.048746        0.818644    9.407654e-07        0.140248   
1654516861         0.050859        0.657282    7.279260e-07        0.182270   
1654518122         0.077481        0.746971    1.106719e-06        0.128185   
1654518122         0.019861        0.742537    8.351244e-07        0.075230   
...                     ...             ...             ...             ...   
32763215           0.071698        0.551390    4.283864e-07        0.115685   
32919890           0.090038        0.725576    5.107756e-07        0.106371   
32950365           0.082743        0.936956    8.907647e-07        0.156956   
32950365           0.052581        0.931744    6.346328e-07        0.226740   
33023659           0.083910        0.644069    8.384629e-07        0.209600   

             y_right_hand_1  z_right_hand_1  x_right_hand_2  y_right_hand_2  \
sequence_id                                                                   
1654240258         0.801060       -0.023933        0.233434        0.779650   
1654240258         0.803662       -0.024834        0.212461        0.778243   
1654516861         0.618362       -0.010041        0.287340        0.581540   
1654518122         0.713794       -0.014445        0.168566        0.666205   
1654518122         0.699494        0.029694        0.141324        0.650860   
...                     ...             ...             ...             ...   
32763215           0.500416        0.020770        0.104263        0.458764   
32919890           0.680378       -0.019299        0.173009        0.628559   
32950365           0.927709       -0.069612        0.228228        0.887516   
32950365           0.882663        0.024502        0.328870        0.832973   
33023659           0.641344       -0.025621        0.319104        0.630722   

             z_right_hand_2  x_right_hand_3  ...  z_left_hand_17  \
sequence_id                                  ...                   
1654240258        -0.059400        0.289391  ...             NaN   
1654240258        -0.065454        0.273581  ...             NaN   
1654516861        -0.054258        0.357401  ...             NaN   
1654518122        -0.042487        0.204207  ...             NaN   
1654518122         0.018943        0.196213  ...             NaN   
...                     ...             ...  ...             ...   
32763215           0.021972        0.100797  ...             NaN   
32919890          -0.049002        0.230754  ...             NaN   
32950365          -0.113111        0.252110  ...             NaN   
32950365           0.028970        0.391947  ...             NaN   
33023659          -0.061089        0.388376  ...             NaN   

             x_left_hand_18  y_left_hand_18  z_left_hand_18  x_left_hand_19  \
sequence_id                                                                   
1654240258              NaN             NaN             NaN             NaN   
1654240258              NaN             NaN             NaN             NaN   
1654516861              NaN             NaN             NaN             NaN   
1654518122              NaN             NaN             NaN             NaN   
1654518122              NaN             NaN             NaN             NaN   
...                     ...             ...             ...             ...   
32763215                NaN             NaN             NaN             NaN   
32919890                NaN             NaN             NaN             NaN   
32950365                NaN             NaN             NaN             NaN   
32950365                NaN             NaN             NaN             NaN   
33023659                NaN             NaN             NaN             NaN   

             y_left_hand_19  z_left_hand_19 

In [ ]:
~(aa['x_right_hand_0'] < 0.1)

sequence_id
1654101738    True
1654101738    True
1654101738    True
1654101738    True
1654101738    True
              ... 
33074178      True
33074178      True
33074178      True
33074178      True
33074178      True
Name: x_right_hand_0, Length: 3665489, dtype: bool

In [ ]:
import numpy as np

np.isnan(aa).sum(axis=1)


sequence_id
33074178     63
33074178     63
33074178    126
33074178    126
33074178     63
           ... 
33074178    126
33074178    126
33074178    126
33074178    126
33074178     63
Length: 72, dtype: int64

In [ ]:
def make_features(self, df):
    '''
    make distance features & vector   per  every frame
    '''

    # make distance
    

    # calculate vectors
    distance_ls = []
    result_ls = []
    
    for frame in df:
        if np.isnan(frame).sum() > 0:
            continue

        distance_ls += [
            torch.cdist(frame, frame).unsqueeze(0)
        ]
        every_vectors_ls = []
        for node in frame:
            node_vector = []
            for other_node in frame:
                node_vector += [(node-other_node).reshape(1,-1)]
            node_vector = torch.concat(node_vector, dim=-1)
            every_vectors_ls += [node_vector]

        every_vectors_ls = torch.concat(every_vectors_ls, dim=0)
        result_ls += [every_vectors_ls.unsqueeze(0)]

    distance = torch.concat(distance_ls, dim=0)
    result = torch.concat(result_ls, dim=0)
    df = torch.concat([df, distance, result], dim=-1)

    return df
            

In [1]:
import pandas as pd

train1 = pd.read_parquet("./data/partial_train_0.parquet")
frame1 = pd.read_parquet("./data/frame0.parquet")
len(set(train1.sequence_id).intersection(set(
    frame1.reset_index('sequence_id').sequence_id
    ))), len(train1)

(19974, 19974)

In [81]:
train1

file_id  sequence_id  \
path                                                        
train_landmarks/522550314.parquet  522550314    765523541   
train_landmarks/522550314.parquet  522550314    765537670   
train_landmarks/522550314.parquet  522550314    765636058   
train_landmarks/522550314.parquet  522550314    765740308   
train_landmarks/522550314.parquet  522550314    765780972   
...                                      ...          ...   
train_landmarks/450474571.parquet  450474571   2147338020   
train_landmarks/450474571.parquet  450474571   2147373562   
train_landmarks/450474571.parquet  450474571   2147437016   
train_landmarks/450474571.parquet  450474571   2147452308   
train_landmarks/450474571.parquet  450474571   2147465106   

                                                         phrase  
path                                                             
train_landmarks/522550314.parquet                      3942 916  
train_landmarks/522550314.parquet                    automotive  
train_landmarks/522550314.parquet              7160 pine slopes  
train_landmarks/522550314.parquet               3202 algoma spr  
train_landmarks/522550314.parquet                   us-v-nagel/  
...                                                         ...  
train_landmarks/450474571.parquet         slworld.net/composers  
train_landmarks/450474571.parquet           +66-979-32-8896-827  
train_landmarks/450474571.parquet  /kamo-vets/verse/sunset-park  
train_landmarks/450474571.parquet                  +55-86-44-54  
train_landmarks/450474571.parquet         +503-8258-19-2264-111  

[19974 rows x 3 columns]

In [4]:
testing = frame1.loc[1604899760]

In [5]:
RIGHT_HAND = []
LEFT_HAND = []
for i in range(21):
    RIGHT_HAND += [f'x_right_hand_{i}', f'y_right_hand_{i}', f'z_right_hand_{i}']
    LEFT_HAND += [f'x_left_hand_{i}', f'y_left_hand_{i}', f'z_left_hand_{i}']


testing = testing[LEFT_HAND].values

In [11]:
df = testing
df = df.reshape(len(df), -1, 3)

In [84]:
%%time
result_ls = []

for frame in df:
    every_vectors_ls = []
    for node in frame:
        node_vector = []
        for other_node in frame:
            node_vector += [(node-other_node).reshape(1,-1)]
        node_vector = torch.concat(node_vector, dim=-1)
        every_vectors_ls += [node_vector]

    every_vectors_ls = torch.concat(every_vectors_ls, dim=0)
    result_ls += [every_vectors_ls.unsqueeze(0)]
# distance = torch.concat(distance_ls, dim=0)
result = torch.concat(result_ls, dim=0)
# df = torch.concat([df, distance, result], dim=-1)


CPU times: user 940 ms, sys: 3.85 ms, total: 944 ms
Wall time: 944 ms


In [33]:
df = torch.tensor(df)

/tmp/ipykernel_159784/2879617888.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  df = torch.tensor(df)


In [34]:
df1 = df[0]

In [83]:
%%time

result_ls = []
for frame in df:
    num_nodes = frame.shape[0]
    to_substract = torch.concat([frame.unsqueeze(0)]*num_nodes, dim=0)
    substracted = frame.unsqueeze(1) - to_substract
    substracted = substracted.reshape(num_nodes,-1).unsqueeze(0)
    result_ls += [substracted]
result1 = torch.concat(result_ls, dim=0)

CPU times: user 12 ms, sys: 3.98 ms, total: 15.9 ms
Wall time: 15.2 ms


In [82]:
frame.shape

torch.Size([21, 3])

In [88]:
def make_distance(df):
    return torch.cdist(df, df)

make_distance(df).shape

torch.Size([351, 21, 21])

In [90]:
adj = torch.randn([21,21])

In [98]:
out = torch.randn([1,181318,21,87])
out.shape

torch.Size([1, 181318, 21, 87])

In [103]:
%%time

torch.matmul(adj, out)

CPU times: user 1.59 s, sys: 1.06 s, total: 2.65 s
Wall time: 531 ms


tensor([[[[-1.3758e+01, -5.4516e+00,  9.0143e+00,  ...,  6.4379e+00,
           -2.1697e+00, -2.3175e+00],
          [ 5.7966e+00,  5.5244e+00,  2.0419e+00,  ...,  1.4600e+00,
            2.8469e-01,  7.3775e-01],
          [ 3.2515e+00,  1.2000e+00, -3.2297e+00,  ..., -6.2415e-01,
           -3.9882e-01, -7.0772e+00],
          ...,
          [ 9.1307e-01,  2.7764e+00, -2.8199e+00,  ...,  2.6280e+00,
            7.3016e-03, -2.8203e+00],
          [ 6.0652e-01, -1.1167e+00, -2.5276e+00,  ...,  1.7104e-02,
            3.9162e+00,  1.8169e+00],
          [-1.2636e+00, -4.4950e-01, -4.2571e+00,  ...,  2.0015e+00,
            3.0756e+00, -1.8579e+00]],

         [[ 5.9847e+00, -1.4165e+00,  2.3785e+00,  ..., -7.3639e+00,
            4.6731e+00,  1.7119e+01],
          [ 9.4469e-01, -5.3175e+00,  5.4040e-01,  ..., -8.3572e+00,
           -9.2616e+00,  6.2589e+00],
          [-1.4679e+00,  1.9352e+00, -3.2615e+00,  ..., -1.3103e+00,
           -7.8906e+00, -8.9239e+00],
          ...,
     

In [61]:
for frame in df:
    every_vectors_ls = []
    for node in frame:
        node_vector = []
        for other_node in frame:
            node_vector += [(node-other_node).reshape(1,-1)]
        node_vector = torch.concat(node_vector, dim=-1)
        every_vectors_ls += [node_vector]
    every_vectors_ls = torch.concat(every_vectors_ls, dim=0)
    # result_ls += [every_vectors_ls.unsqueeze(0)]
    break

In [65]:
every_vectors_ls

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.2313, -0.0044,  0.1267],
        [-0.0684, -0.0593,  0.0243,  ...,  0.1630, -0.0636,  0.1510],
        [-0.1662, -0.0927,  0.0110,  ...,  0.0651, -0.0971,  0.1377],
        ...,
        [-0.2756,  0.0015, -0.1532,  ..., -0.0442, -0.0028, -0.0265],
        [-0.2623,  0.0076, -0.1377,  ..., -0.0309,  0.0032, -0.0110],
        [-0.2313,  0.0044, -0.1267,  ...,  0.0000,  0.0000,  0.0000]])

In [28]:
df = torch.tensor(df)

result_ls = []

for frame in df:
    every_vectors_ls = []
    for node in frame:
        node_vector = []
        for other_node in frame:
            node_vector += [(node-other_node).reshape(1,-1)]
        node_vector = torch.concat(node_vector, dim=-1)
        every_vectors_ls += [node_vector]

    every_vectors_ls = torch.concat(every_vectors_ls, dim=0)
    result_ls += [every_vectors_ls.unsqueeze(0)]

result = torch.concat(result_ls, dim=0)


/tmp/ipykernel_159784/3999449050.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  df = torch.tensor(df)


In [41]:
node_vector.shape

torch.Size([1, 63])

In [31]:
result.shape

torch.Size([351, 21, 63])

In [40]:
torch.roll(df1, 1, dims=0)

tensor([[ 6.1905e-01,  6.8233e-01, -1.2670e-01],
        [ 8.5040e-01,  6.7794e-01, -4.3759e-07],
        [ 7.8204e-01,  6.1869e-01,  2.4271e-02],
        [ 6.8417e-01,  5.8522e-01,  1.0985e-02],
        [ 5.8777e-01,  5.7916e-01, -8.5436e-03],
        [ 5.1681e-01,  5.8609e-01, -3.2603e-02],
        [ 6.6194e-01,  5.4265e-01, -4.8953e-02],
        [ 5.1735e-01,  5.3926e-01, -7.7825e-02],
        [ 4.3764e-01,  5.4462e-01, -9.3127e-02],
        [ 3.7433e-01,  5.4849e-01, -1.0459e-01],
        [ 6.7686e-01,  5.7534e-01, -8.3146e-02],
        [ 5.0520e-01,  5.8096e-01, -1.0676e-01],
        [ 4.0929e-01,  5.9161e-01, -1.1256e-01],
        [ 3.4155e-01,  5.9975e-01, -1.2298e-01],
        [ 6.8839e-01,  6.1774e-01, -1.1166e-01],
        [ 5.2815e-01,  6.3699e-01, -1.2742e-01],
        [ 5.4636e-01,  6.5108e-01, -1.0933e-01],
        [ 5.8627e-01,  6.5511e-01, -1.0096e-01],
        [ 6.9507e-01,  6.6295e-01, -1.3860e-01],
        [ 5.7485e-01,  6.7948e-01, -1.5315e-01],
        [ 5.8815e-01

In [37]:
df1

tensor([[ 8.5040e-01,  6.7794e-01, -4.3759e-07],
        [ 7.8204e-01,  6.1869e-01,  2.4271e-02],
        [ 6.8417e-01,  5.8522e-01,  1.0985e-02],
        [ 5.8777e-01,  5.7916e-01, -8.5436e-03],
        [ 5.1681e-01,  5.8609e-01, -3.2603e-02],
        [ 6.6194e-01,  5.4265e-01, -4.8953e-02],
        [ 5.1735e-01,  5.3926e-01, -7.7825e-02],
        [ 4.3764e-01,  5.4462e-01, -9.3127e-02],
        [ 3.7433e-01,  5.4849e-01, -1.0459e-01],
        [ 6.7686e-01,  5.7534e-01, -8.3146e-02],
        [ 5.0520e-01,  5.8096e-01, -1.0676e-01],
        [ 4.0929e-01,  5.9161e-01, -1.1256e-01],
        [ 3.4155e-01,  5.9975e-01, -1.2298e-01],
        [ 6.8839e-01,  6.1774e-01, -1.1166e-01],
        [ 5.2815e-01,  6.3699e-01, -1.2742e-01],
        [ 5.4636e-01,  6.5108e-01, -1.0933e-01],
        [ 5.8627e-01,  6.5511e-01, -1.0096e-01],
        [ 6.9507e-01,  6.6295e-01, -1.3860e-01],
        [ 5.7485e-01,  6.7948e-01, -1.5315e-01],
        [ 5.8815e-01,  6.8550e-01, -1.3772e-01],
        [ 6.1905e-01

In [2]:
import pandas as pd
df = pd.read_parquet('./data/partial_train_0.parquet')

In [3]:
%%time

frame = pd.read_parquet('./data/frame0.parquet')

CPU times: user 4.45 s, sys: 1.52 s, total: 5.97 s
Wall time: 739 ms


In [5]:
frame.loc[[955164628]]

x_right_hand_0  y_right_hand_0  z_right_hand_0  x_right_hand_1  \
sequence_id                                                                   
955164628          0.604159        0.646978   -1.487092e-07        0.621562   

             y_right_hand_1  z_right_hand_1  x_right_hand_2  y_right_hand_2  \
sequence_id                                                                   
955164628          0.633111        0.019673        0.645518        0.625919   

             z_right_hand_2  x_right_hand_3  ...  z_left_hand_17  \
sequence_id                                  ...                   
955164628           0.02437        0.665151  ...             NaN   

             x_left_hand_18  y_left_hand_18  z_left_hand_18  x_left_hand_19  \
sequence_id                                                                   
955164628               NaN             NaN             NaN             NaN   

             y_left_hand_19  z_left_hand_19  x_left_hand_20  y_left_hand_20  \
sequence_id                                                                   
955164628               NaN             NaN             NaN             NaN   

             z_left_hand_20  
sequence_id                  
955164628               NaN  

[1 rows x 126 columns]

In [4]:
frame.loc[1604899760]

x_right_hand_0  y_right_hand_0  z_right_hand_0  x_right_hand_1  \
sequence_id                                                                   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
...                     ...             ...             ...             ...   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   

             y_right_hand_1  z_right_hand_1  x_right_hand_2  y_right_hand_2  \
sequence_id                                                                   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
...                     ...             ...             ...             ...   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   
1604899760              NaN             NaN             NaN             NaN   

             z_right_hand_2  x_right_hand_3  ...  z_left_hand_17  \
sequence_id                                  ...                   
1604899760              NaN             NaN  ...       -0.138603   
1604899760              NaN             NaN  ...       -0.121943   
1604899760              NaN             NaN  ...       -0.119124   
1604899760              NaN             NaN  ...       -0.099394   
1604899760              NaN             NaN  ...       -0.133879   
...                     ...             ...  ...             ...   
1604899760              NaN             NaN  ...       -0.031759   
1604899760              NaN             NaN  ...       -0.036097   
1604899760              NaN             NaN  ...       -0.043281   
1604899760              NaN             NaN  ...       -0.049974   
1604899760              NaN             NaN  ...       -0.084228   

             x_left_hand_18  y_left_hand_18  z_left_hand_18  x_left_hand_19  \
sequence_id                                                                   
1604899760         0.574848        0.679480       -0.153153        0.588145   
1604899760         0.535379        0.662012       -0.131416        0.562967   
1604899760         0.494226        0.651346       -0.123309        0.518719   
1604899760         0.469581        0.651159       -0.092952        0.500384   
1604899760         0.441494        0.651873       -0.149539        0.472407   
...                     ...             ...             ...             ...   
1604899760         0.596478        0.599519       -0.057592        0.575766   
1604899760         0.605144        0.604827       -0.068332        0.581444   
1604899760         0.633546        0.617642       -0.080174        0.609072   
1604899760         0.666496        0.639988       -0.087179        0.633740   
1604899760         0.741398        0.684600       -0.131227        0.707953   

             y_left_hand_19  z_left_hand_19 

In [5]:
6%3

0

In [6]:
frame.loc[765523541]

frame,loc['765523541']

x_right_hand_0  y_right_hand_0  z_right_hand_0  x_right_hand_1  \
sequence_id                                                                   
765523541          0.271300        0.823856        0.000001        0.362784   
765523541          0.253725        0.833073        0.000002        0.352714   
765523541          0.268294        0.810972        0.000001        0.365343   
765523541          0.286671        0.811448        0.000001        0.373863   
765523541          0.262001        0.818015        0.000001        0.366714   
765523541          0.256688        0.823894        0.000001        0.365157   
765523541          0.250264        0.817964        0.000001        0.353846   
765523541               NaN             NaN             NaN             NaN   
765523541          0.235284        0.825899        0.000002        0.340346   
765523541          0.248744        0.843656        0.000002        0.345759   
765523541          0.247889        0.847189        0.000002        0.344842   
765523541          0.252014        0.849627        0.000002        0.354130   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541          0.242217        0.836811        0.000002        0.343983   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541          0.266664        0.838851        0.000001        0.353313   
765523541          0.256785        0.828736        0.000001        0.340693   
765523541          0.267890        0.837105        0.000001        0.360795   
765523541          0.268301        0.838928        0.000001        0.374292   
765523541          0.251071        0.815391        0.000002        0.339635   
765523541          0.245934        0.830101        0.000003        0.338117   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN             NaN   
765523541               NaN             NaN             NaN    

In [ ]:
# Loop through each file_id
for file_id in tqdm(dataset_df.file_id.unique()):
    # Parquet file name
    pq_file = f"/kaggle/input/asl-fingerspelling/train_landmarks/{file_id}.parquet"
    # Filter train.csv and fetch entries only for the relevant file_id
    file_df = dataset_df.loc[dataset_df["file_id"] == file_id]
    # Fetch the parquet file
    parquet_df = pq.read_table(f"/kaggle/input/asl-fingerspelling/train_landmarks/{str(file_id)}.parquet",
                              columns=['sequence_id'] + FEATURE_COLUMNS).to_pandas()
    # File name for the updated data
    tf_file = f"preprocessed/{file_id}.tfrecord"
    parquet_numpy = parquet_df.to_numpy()
    # Initialize the pointer to write the output of 
    # each `for loop` below as a sequence into the file.
    with tf.io.TFRecordWriter(tf_file) as file_writer:
        # Loop through each sequence in file.
        for seq_id, phrase in zip(file_df.sequence_id, file_df.phrase):
            # Fetch sequence data
            frames = parquet_numpy[parquet_df.index == seq_id]
            
            # Calculate the number of NaN values in each hand landmark
            r_nonan = np.sum(np.sum(np.isnan(frames[:, RHAND_IDX]), axis = 1) == 0)
            l_nonan = np.sum(np.sum(np.isnan(frames[:, LHAND_IDX]), axis = 1) == 0)
            no_nan = max(r_nonan, l_nonan)
            
            if 2*len(phrase)<no_nan:
                features = {FEATURE_COLUMNS[i]: tf.train.Feature(
                    float_list=tf.train.FloatList(value=frames[:, i])) for i in range(len(FEATURE_COLUMNS))}
                features["phrase"] = tf.train.Feature(bytes_list=tf.train.BytesList(value=[bytes(phrase, 'utf-8')]))
                record_bytes = tf.train.Example(features=tf.train.Features(feature=features)).SerializeToString()
                file_writer.write(record_bytes)

In [2]:
import torch
import torch.nn as nn

# Target are to be padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch (padding length)
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

 # Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()


In [3]:
input.shape

torch.Size([50, 16, 20])

In [5]:
target.shape

torch.Size([16, 30])

In [6]:
input_lengths.shape

torch.Size([16])

In [7]:
target_lengths.shape

torch.Size([16])